### ISSUE TITLE
Alternative Licensing

### ISSUE THREAD

**Issue by ismaell** [screen-editor/se#11]
Please provide an alternative licensing option.

Public Domain is harmful/problematic, because it's regulated differently depending on the country, and in some the [regime requires payment](https://en.wikipedia.org/wiki/Paying_public_domain). E.g. in Argentina and Uruguay, any use of the work, even non-commercial, requires paying a fee to the state, so lawful use is impaired, and crearly against the intent/spirit of putting it in PD.

**Comment by mndrix** [comment]
If there is a change to the license (which I support), my vote is for [0BSD](http://landley.net/toybox/license.html). Its terms come close to the intent of public domain. I also enjoy that the license text is not viral.

**Comment by josephholsten** [comment]
Some guidance about the above: http://copyfree.org/policy/public

I’m also a fan of 0BSD (which copyfree.org calls the Toybox License) or ISC. Applying a license to new distribution methods of works previously in public domain is generally considered fine. (See the [0BSD page](http://landley.net/toybox/license.html), “But if some random third party [takes public domain code](https://github.com/mkj/dropbear/blob/master/libtomcrypt/LICENSE) and slaps [some other license on it](http://www.opensource.apple.com/source/gnuzip/gnuzip-25/gzip/gzip.c), then it's fine.” That second link is to gnuzip as distributed by Apple. If FSF & Apple think it’s acceptable, we can too.)

**Comment by SirWumpus** [comment]
`0BSD` is good as a clearer public domain license, though maybe a `BSD-1-clause` license would be better and can be used to at least provide author(s) credit.

**Comment by ismaell** [comment]
IANAL, but I'm not sure if you can remove a copyright notice no matter the license (unless perhaps if it explicitly gives you that permission), so that clause in `BSD-1-license` might be redundant...
