### ISSUE TITLE
config.in missing

### ISSUE THREAD

**Issue by SirWumpus** [screen-editor/se#15]
Trying to clean up the `configure` et al. process.  I'm pretty close, but running `automake` results in:
```
elf$ automake
configure.ac:93: error: required file 'config.in' not found
```

See `configure.ac`
```
configure.ac:AC_CONFIG_HEADERS([config.h:config.in])
```

**Comment by tcort** [comment]
I don't keep generated files in source control, I just keep the essentials... `configure.ac`, `Makefile.am`, etc. The generated files *are* included in the release tarballs (e.g. the `configure` script).

To generate all of the auto-stuff:

```
autoreconf -i --force
rm -rf autom4te.cache
```

Then build the GNU way:

```
./configure
make
make install
```
