### ISSUE TITLE
Illegal address error entering insert mode on an empty buffer

### ISSUE THREAD

**Issue by tcort** [screen-editor/se#4]
I received this report via e-mail and can confirm the results:

```
the `i` command, when executed on the empty buffer in `ed` is a valid entry into input mode,
but on `se` is throwing an illegal address error.
```

Further investigation is needed to determine if it should be allowed and how to allow it.

**Comment by SirWumpus** [comment]
From POSIX.2 draft 12 `ed(1)` you can say `0a` or `1i` (zero not permitted for `i` command).  One way to address this would be to treat `yi` commands, where 'y' is a line number, as an alias for `(y-1)a`.

**Comment by tcort** [comment]
merged. Thanks, @SirWumpus !
