### ISSUE TITLE
Autoconf errors when building on Ubuntu 14.04

### ISSUE THREAD

**Issue by danlm** [screen-editor/se#8]
configure.ac:10: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AM_SILENT_RULES

**Comment by mndrix** [comment]
Running `autoreconf -fi`, should generate the files you want and avoid the errors. (`-f` rebuilds files even if they haven't changed; `-i` installs any missing files.) At this point, `./configure` should work.

More detail: `autoreconf -fi` may show warnings like these:

```
configure.ac:18: warning: The macro `AC_ISC_POSIX' is obsolete.
configure.ac:18: You should run autoupdate.
/usr/local/share/autoconf-2.71/autoconf/specific.m4:550: AC_ISC_POSIX is expanded from...
configure.ac:18: the top level
configure.ac:59: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:59: You should run autoupdate.
/usr/local/share/autoconf-2.71/autoconf/headers.m4:712: AC_HEADER_STDC is expanded from...
configure.ac:59: the top level
```

As the message says, you can run `autoupdate` to fix those warnings.  If you want to remove all warnings, you'll also have to manually edit `configure.ac` to remove the section about `STDC_HEADERS`.
